### ISSUE TITLE
SCRIPT ERROR: _enter_tree: Invalid call. Nonexistent function 'speak' in base 'Reference (TTSDriver.gdns)'.

### ISSUE THREAD

**Issue by ndarilek** [bruvzg/godot_tts#1]
Thanks for doing this work! I'm trying to integrate this plugin into my [godot-accessibility work](https://gitlab.com/lightsoutgames/godot-accessibility). To do this, I added the following to addons/accessibility/accessibility.gd:

```
const TTSDriver = preload("res://TTSDriver.gdns")
var tts
...
func _enter_tree():
    tts = TTSDriver.new()
    print(tts)
    tts.speak("Hello world", true)
```

The goal here is to replace bunches of `print()` calls with this TTS module, but first I'd like to just get "hello world" working. Unfortunately, I get:

```
SCRIPT ERROR: _enter_tree: Invalid call. Nonexistent function 'speak' in base 'Reference (TTSDriver.gdns)'.
   At: res://addons/accessibility/accessibility.gd:41.
```

when running `godot -e`. I basically unzipped your Linux release into the root of the checked-out godot-accessibility project, then ran the editor.

Any idea what may be going on here? `ldd` on the 64-bit .so file doesn't show any missing libs, so everything on my system should be fine. Maybe I'm missing a project integration step?

**Comment by bruvzg** [comment]
>Any idea what may be going on here? ldd on the 64-bit .so file doesn't show any missing libs, so everything on my system should be fine. Maybe I'm missing a project integration step?

It's not linux specific. I got same error on macOS as well.

Looks like to use gdnative module in the editor plugin, it should be registered as `tool class` in addition to normal `class`, which I missed.

Issue should be fixed by 726a1d8a3cb8aa45af5939c2622fee0982cda2b6.

New release files: https://github.com/bruvzg/godot_tts/releases/tag/0.1.0-1
