### ISSUE TITLE
HTML5 support?

### ISSUE THREAD

**Issue by metinc** [bruvzg/godot_tts#2]
I tried the latest release in HTML5 but there were no voices in the drop down (tested in Firefox and Edge). Could you guide me in the right direction where to start in order to add HTML5 support?

**Comment by bruvzg** [comment]
HTML5 is not supported, since there's no GDNative support for HTML5 at all.

It is planned to implement GDNative support (see https://godotengine.org/article/godot-web-progress-report-3), but currently there is no way to use modules in HTML5 exports.
