### ISSUE TITLE
Update to godot 3.3

### ISSUE THREAD

**Issue by sairam4123** [bruvzg/godot_tts#3]
Hi. I am a game developer and I'd like to use your TTS plugin, if you don't mind could you please update this to Godot 3.3?
Thank you so much for making this!

**Comment by bruvzg** [comment]
Is there anything in particular that is not working and require updating? The last release seems to work fine (at least on macOS) with 3.3.2 stable and current 3.4 custom builds.

**Comment by sairam4123** [comment]
I hope you please update the readme then haha. I thought this wouldn't work.

**Comment by wpshadow** [comment]
Hi, does anyone have an update or an idea how to fix tts in 3.3? I could really need it in my game... I try to make my (robot) NPCs a bit more interesting... TTS would be a great way but I have the same issue...

**Comment by sairam4123** [comment]
it worked for me in 3.3.3 tho, I guess something's wrong with your computer.
Also this uses OS's Text to speech, if the end user didn't install Text to speech then your game will crash, I haven't really tested it, but I guess that might be a problem.

**Comment by wpshadow** [comment]
The strange thing is that the system is telling me a dll - File is missing:

E 0:00:03.464   open_dynamic_library: Can't open dynamic library: C:/Users/wpsha/Downloads/godot_tts-master/godot_tts-master/demo/libgdtts/libgdtts.windows.x86_64.dll, error: Error 126: The specified module was not found.

**Comment by bruvzg** [comment]
Are you building your own library (with MinGW or MSVC?) or using one from releases?

**Comment by wpshadow** [comment]
I tried the one from the releases but now I have to kill my pc... I just realized, that my antivirus just deleted the dll - file... Please excuse me for wasting your time. After I stopped the antivirus it works without any troubles... Sorry for that!
