### ISSUE TITLE
Pitch adjustment

### ISSUE THREAD

**Issue by IvailoBurov** [bruvzg/godot_tts#4]
Hello, great plugin!
Is it possible to add Pitch adjustment?
With this functionality you will be able to simulate the voices of multiple characters.
Thanks in advance.

**Comment by bruvzg** [comment]
Pitch support was added in #5 (`tts.set_pitch(float)`). Available range and granularity depends on OS and voice (quite small difference on Windows, a bit bigger on macOS, not tested on Linux).
